package com.investment.user.entity;

import java.math.BigDecimal;
import java.util.Date;

public class HxBondRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.APPLY_NO
     *
     * @mbg.generated
     */
    private String applyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.CONTRACT_NO
     *
     * @mbg.generated
     */
    private String contractNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.USER_NO
     *
     * @mbg.generated
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.LENDER_CODE
     *
     * @mbg.generated
     */
    private String lenderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.FUND_CODE
     *
     * @mbg.generated
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.CONTRACT_AMT
     *
     * @mbg.generated
     */
    private BigDecimal contractAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.HAND_AMT
     *
     * @mbg.generated
     */
    private BigDecimal handAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bond_relation.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.ID
     *
     * @return the value of hx_bond_relation.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.ID
     *
     * @param id the value for hx_bond_relation.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.APPLY_NO
     *
     * @return the value of hx_bond_relation.APPLY_NO
     *
     * @mbg.generated
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.APPLY_NO
     *
     * @param applyNo the value for hx_bond_relation.APPLY_NO
     *
     * @mbg.generated
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo == null ? null : applyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.CONTRACT_NO
     *
     * @return the value of hx_bond_relation.CONTRACT_NO
     *
     * @mbg.generated
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.CONTRACT_NO
     *
     * @param contractNo the value for hx_bond_relation.CONTRACT_NO
     *
     * @mbg.generated
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.USER_NO
     *
     * @return the value of hx_bond_relation.USER_NO
     *
     * @mbg.generated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.USER_NO
     *
     * @param userNo the value for hx_bond_relation.USER_NO
     *
     * @mbg.generated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.LENDER_CODE
     *
     * @return the value of hx_bond_relation.LENDER_CODE
     *
     * @mbg.generated
     */
    public String getLenderCode() {
        return lenderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.LENDER_CODE
     *
     * @param lenderCode the value for hx_bond_relation.LENDER_CODE
     *
     * @mbg.generated
     */
    public void setLenderCode(String lenderCode) {
        this.lenderCode = lenderCode == null ? null : lenderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.FUND_CODE
     *
     * @return the value of hx_bond_relation.FUND_CODE
     *
     * @mbg.generated
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.FUND_CODE
     *
     * @param fundCode the value for hx_bond_relation.FUND_CODE
     *
     * @mbg.generated
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.CONTRACT_AMT
     *
     * @return the value of hx_bond_relation.CONTRACT_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getContractAmt() {
        return contractAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.CONTRACT_AMT
     *
     * @param contractAmt the value for hx_bond_relation.CONTRACT_AMT
     *
     * @mbg.generated
     */
    public void setContractAmt(BigDecimal contractAmt) {
        this.contractAmt = contractAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.HAND_AMT
     *
     * @return the value of hx_bond_relation.HAND_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getHandAmt() {
        return handAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.HAND_AMT
     *
     * @param handAmt the value for hx_bond_relation.HAND_AMT
     *
     * @mbg.generated
     */
    public void setHandAmt(BigDecimal handAmt) {
        this.handAmt = handAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.CREATE_BY
     *
     * @return the value of hx_bond_relation.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.CREATE_BY
     *
     * @param createBy the value for hx_bond_relation.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.CREATE_DATE
     *
     * @return the value of hx_bond_relation.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.CREATE_DATE
     *
     * @param createDate the value for hx_bond_relation.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.UPDATE_BY
     *
     * @return the value of hx_bond_relation.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.UPDATE_BY
     *
     * @param updateBy the value for hx_bond_relation.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.UPDATE_DATE
     *
     * @return the value of hx_bond_relation.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.UPDATE_DATE
     *
     * @param updateDate the value for hx_bond_relation.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.DEL_FLAG
     *
     * @return the value of hx_bond_relation.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.DEL_FLAG
     *
     * @param delFlag the value for hx_bond_relation.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bond_relation.REMARKS
     *
     * @return the value of hx_bond_relation.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bond_relation.REMARKS
     *
     * @param remarks the value for hx_bond_relation.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}