package com.investment.user.mapper;

import com.investment.user.entity.HxBondRelation;

public interface HxBondRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bond_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bond_relation
     *
     * @mbg.generated
     */
    int insert(HxBondRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bond_relation
     *
     * @mbg.generated
     */
    int insertSelective(HxBondRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bond_relation
     *
     * @mbg.generated
     */
    HxBondRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bond_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HxBondRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bond_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HxBondRelation record);
}